version: '3'
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://jhonny:bdfs123@db/fullstackbd
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstackbd
      MYSQL_USER: jhonny
      MYSQL_PASSWORD: bdfs123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
